# creating roles for ressources
apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRole
metadata:
  name: orleans-manager
rules:
- apiGroups: ["orleans.dot.net"] 
  resources: ["clusterversions", "silos"] 
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]