---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: silo-pod-reader-binding
subjects:
- kind: ServiceAccount
  name: {{ include "api.serviceAccountName" . }}
  apiGroup: ''
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: ''
