---
# granting access for: system:serviceaccount:hypomos-dev:default
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-orleans
subjects:
- kind: ServiceAccount
  name: {{ include "api.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: orleans-manager
  apiGroup: rbac.authorization.k8s.io
